### PR TITLE
Remove outdated HB config setting

### PR DESCRIPTION
**Pull request by ksaur**
Thanks to the PR (https://github.com/microsoft/hummingbird/pull/523) from @xadupre , we should be able to remove the version pin for Hummingbird.

### CODE REVIEW

**Comment by xadupre** [comment]
This PR probably requires #471 to be merged first to fix some issues with lightgbm.

**Comment by ksaur** [comment]
In addition to needing that PR, we have some additional work to do in the LGBM code (fixing an API change).

**Comment by ksaur** [comment]
Installing `torch==1.9.x` (most current) is giving a memory error in the az pipeline; i'm not sure what to do about that.

**Comment by xadupre** [comment]
#471 was merged. It is worth updating the PR and try again.

**Comment by ksaur** [comment]
As it is now, this PR just removes the outdated line, already commented out.  

Closing.

**Pull request closed without merging**
